błąd: "Błąd"
pytanie: "Pytanie"
ulepszenie: "Ulepszenie"
redundancja: "Redundancja"
ciasteczka/RODO: 'Komunikat dot. ciasteczek\/polityki prywatności\/RODO'
social: "Element społecznościowy"
popup: "Wyskakujące okienko"
