dist: xenial
addons:
  apt:
    packages:
    - language-pack-pl
notifications:
  email:
    on_success: never
    on_failure: always
language: bash
script:
- "./scripts/VICHS_auto.sh"
env:
  global:
    secure: R/BMsIyAKyR6g8VVzK/9bsYofSu77sRBDTF5TuJi+jUNcPgfI2wTmiFRWbIonq5Em5r4TNBXjSTQZ3u0uYfvdoeIg28l705W+B0hUWpll3gEFeKLP9wGcuIWZVESCwnDDhULjwVNPbB9Y19hSyfWzkUF/xvkbm9vcAlnv48DHfUFrUxjnA4zK7xAn+CKjF7sQC73D1RwvPSQ8Vh0jotdSjhOLmINGEwZPCdW4To/mSptJjaTt62VVzlcLsxM6Aqc0bABUMsorvfmV/LOrj8vP876X42pRWn5ibcE+blD1MI9IrgvHS9xJLlSQ1/aL44BTDp5ALRDp59nrp1k+IF69NsfZoOx7OLt4WSiB/d39PjFTJti0+gcNOP66OJiNoajty+EO+sr9UyHhHQTj5kfCbUu1VKA2idHBUXIlAwqjMStoub28RZk5PcM7deRKiEW/euojKIgDJBOvWpidUSdDbKF3tfihFdmADB9wzCDleZXpJ3ooRB2RshBMfwnnZkQw18t/WCj89w/2mN22h5P1XmCOk0GZ62aPx81o1/pf7+C18qb0/mYTnoMIzUDTaJ831YhfmESE1fhKG0tBMm7yPJKjm4dfnM/TXEot85841xKK22VIayuIjM/6wx+fkU7Wc2UilXnI1zop8c6b0BOJgSzaNvhawdtBMhqef8yk/U=
