blank_issues_enabled: false
contact_links:
  - name: Off-topic
    url: https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/discussions/new
    about: Życzenia, powitania i inne sprawy niezwiązane z listami filtrów, czyli plotkujemy o wszystkim i o niczym 🙂
